### ISSUE TITLE
Without node js solution available here

### ISSUE THREAD

**Issue by savsani** [acdb-team/google-sheets-to-json#17]
You can get Google Sheets data into JSON using 2 Methods. (1) Using **Google Apps Script** (2) Using **Google Sheets API v4**. There is a nice script available on [Codester](https://www.codester.com/items/30840/google-sheets-to-json?ref=WebVista) for getting google sheets data as JSON. It comes with easy step by step tutorial for how to. Example of Dynamic HTML table from google sheets data as JSON also included in it. Sample code examples for Javascript, jQuery & PHP are also given there.

**Comment by LavaToaster** [comment]
I'm not really sure what you're hoping to get here. You're trying to advertise a paid generic google sheets to json script, whereas this repo is dedicated to a parsing a specific google sheet and exposing some opinionated json from it.
