### ISSUE TITLE
Add usage to README

### ISSUE THREAD

**Issue by quanuw** [acdb-team/google-sheets-to-json#3]
@LavaToaster This looks like a promising project! Our team is trying to pull ACNH item data from google sheets to json. Can you please give some usage samples?

**Comment by defelper** [comment]
I doing that: 

Install yarn and do: 
`yarn install `

then execute to update .json files 
`sh bin/build.sh `

**Comment by Stun3R** [comment]
@defelper @quanuw We are working on it  😄 

You can just add the package with yarn or npm:

`yarn add @nooksbazaar/acdb`
`npm install --save @nooksbazaar/acdb`

And then you can use it in your project with import or require

**Comment by genesy** [comment]
@Stun3R can you add instructions how to build? I'm trying to run the build script but it only updates the ts files. is the credentials.json file required or optional? I'm trying to rebuild because the dates are a day off

**Comment by LavaToaster** [comment]
This was added as of #8 :)

Thanks @magus and @iamcal!
